search_tweets_api:
  bearer_token: AAAAAAAAAAAAAAAAAAAAAPU4KAEAAAAAkKnz4UbihlsZPNjA926x%2BCb1lFc%3DqWVBcM05Ge2HR6lt1KgY4Q3vnbpLkC5Z5Qi0WFlrFWQOc9QkIP
azure:
  subscription_key: VdPRDAqaAA2xwthx8pmx8PlbFLuDTpSOw8vpwlCF1Ti1whBQDF